Repository mia-platform-marketplace/public-catalog, pull requests merged in 2025-07, with the labels that each got.

#224 ci(workflow): remove unused cosign flag
  .github/workflows/_release-docker.yml
Labels: github_actions

#223 feat(catalog): update data-catalog-application to bump job-runner to v0.2.3
  items/application/data-catalog-application/versions/NA.json
  tests/integration.test.ts.snapshot
Labels: catalog content

#237 feat(catalog): add new plugin data-fabric-mongezium-cdc
  items/plugin/data-fabric-mongezium-cdc/assets/mongezium_logo_20250708.png
  items/plugin/data-fabric-mongezium-cdc/versions/0.4.0.json
  tests/integration.test.ts.snapshot
Labels: catalog content

#249 fix(sync): fixed import type and updated README.md
  Makefile
  README.md
  default.env
  src/lib/override-items-fields.ts
Labels: sync script

#251 feat: new integration connector agent versions and template
  CONTRIBUTING.md
  items/plugin/integration-connector-agent/versions/0.3.0.json
  items/plugin/integration-connector-agent/versions/0.4.0.json
  items/template/integration-connector-agent-processor/assets/integration-connector-agent_logo_20250423.png
  items/template/integration-connector-agent-processor/versions/0.1.0.json
  tests/integration.test.ts.snapshot
Labels: catalog content

#257 feat(catalog): added integration connector agent v0.5.0
  items/plugin/integration-connector-agent/versions/0.5.0.json
  tests/integration.test.ts.snapshot
Labels: catalog content
