Repository mia-platform-marketplace/public-catalog, pull requests merged in 2025-03, with the labels that each got.

#20 feat: improve Catalog items validation checks
  CONTRIBUTING.md
  items/applications/identification-manager/versions/NA.json
  items/applications/insurance-crud-data-model/versions/NA.json
  items/applications/manifest.schema.json
  items/applications/payment-integration-hub/versions/NA.json
  items/applications/therapy-device-module/versions/NA.json
  items/examples/manifest.schema.json
  items/plugins/manifest.schema.json
  items/proxies/manifest.schema.json
  items/sidecars/manifest.schema.json
  items/templates/manifest.schema.json
  package.json
  scripts/check-items.ts
  tests/integration.test.ts.snapshot
  yarn.lock
Labels: enhancement

#21 chore(docs): update contribution guidelines
  CONTRIBUTING.md
Labels: documentation

#22 feat(catalog): update version 1.0.0 of vite-typescript-react-template
  CONTRIBUTING.md
  items/templates/vite-typescript-react-template/versions/1.0.0.json
  tests/integration.test.ts.snapshot
Labels: catalog content

#24 feat(catalog): update version NA of application fast-data-control-plane
  items/applications/fast-data-control-plane/versions/NA.json
  tests/integration.test.ts.snapshot
Labels: catalog content

#26 feat(catalog): add new plugin integration-connector-agent
  items/plugins/integration-connector-agent/assets/integration-connector-agent.png
  items/plugins/integration-connector-agent/versions/0.2.0.json
  package.json
  tests/integration.test.ts.snapshot
Labels: catalog content

#34 feat: add support to YAML manifests
  .vscode/settings.json
  CONTRIBUTING.md
  README.md
  package.json
  scripts/check-items.ts
  src/lib/collect-items.ts
  yarn.lock
Labels: enhancement

#36 feat(catalog): add version 6.8.1 to plugin single-view-creator-low-code-mongodb
  items/plugins/single-view-creator-low-code-mongodb/versions/6.8.1.json
  tests/integration.test.ts.snapshot
Labels: catalog content

#35 feat(catalog): add version 6.8.1 to plugin single-view-creator-low-code-kafka
  items/plugins/single-view-creator-low-code-kafka/versions/6.8.1.json
  tests/integration.test.ts.snapshot
Labels: catalog content

#19 ci: docker release workflow
  .github/workflows/_release-docker.yml
  .github/workflows/main.yml
Labels: github_actions

#40 fix(sync): fix isLatest handling when DB is not empty
  src/lib/collect-items.ts
  src/lib/sync-items.ts
  tests/integration.test.ts
Labels: bug, sync script

#41 feat(sync): improve script results logging
  package.json
  src/index.ts
  src/lib/assets.ts
  src/lib/metrics.ts
  src/lib/sync-categories.ts
  src/lib/sync-items.ts
  src/lib/types.d.ts
  src/lib/utils.ts
  tests/integration.test.ts
  tests/integration.test.ts.snapshot
  yarn.lock
Labels: enhancement, sync script

#52 feat(catalog): update version 1.0.0 of template data-catalog
  items/templates/data-catalog/versions/1.0.0.json
  tests/integration.test.ts.snapshot
Labels: catalog content

#53 feat(catalog): add new sidecar audit-trail
  items/sidecars/audit-trail/assets/audit-trail-logo.png
  items/sidecars/audit-trail/versions/NA.json
  tests/integration.test.ts.snapshot
Labels: catalog content

#73 feat(catalog): update version NA of application user-manager-module
  items/applications/user-manager-module/versions/NA.json
  tests/integration.test.ts.snapshot
Labels: catalog content

#71 feat(catalog): update version NA of application notification-module
  items/applications/notification-module/versions/NA.json
  tests/integration.test.ts.snapshot
Labels: catalog content

#70 feat(catalog): update version NA of application ehr-module
  items/applications/ehr-module/versions/NA.json
  tests/integration.test.ts.snapshot
Labels: catalog content

#69 feat(catalog): update version NA of application booking-module
  items/applications/booking-module/versions/NA.json
  tests/integration.test.ts.snapshot
Labels: catalog content
